module.exports.config = {
  name: "goibot",
  version: "4.0.0",
  hasPermssion: 0,
  credits: "AHMAD RDX",
  description: "300+ Massive Pure Desi Funny, GF-BF Flirting & Nakhre Dialogues",
  commandCategory: "Noprefix",
  usages: "noprefix",
  cooldowns: 1,
};

module.exports.handleEvent = async function({ api, event, Users }) {
  const { threadID, messageID, body, senderID } = event;
  if (!body || senderID == api.getCurrentUserID()) return;

  // 🔥 TRIGGER CHECK
  if (body.toLowerCase().indexOf("bot") !== 0) return;

  const name = await Users.getNameUser(senderID);

  // 👑 ROYAL BOX LAYOUT FRAME
  function createFrame(userName, replyMsg) {
    return `┏━━ ✨ 𝐀𝐇𝐌𝐀𝐃 𝐑𝐃𝐗 ✨ ━━┓\n\n` +
           `  👤 𝖧𝖾𝗒, ${userName} !\n\n` +
           `  💬 ${replyMsg}\n\n` +
           `┗━━━━━━━━━━━━━┛`;
  }

  // 🎭 MASSIVE 300 DESI FUNNY, GF-BF DRAMA & NAKHRE DIALOGUES
  const tl = [
    // --- GF-BF, FLIRTING & LOVE DRAMA ---
    "Haye Jaanu! Itna sacha pyaar? Kahin sach mein shaadi ka iraada toh nahi? 💍",
    "Suno na, dunya ek taraf aur aapki baatein ek taraf... bilkul fuzool! 🌍",
    "Oye bhabhi ka phone aa raha hai tumhare, jaldi se chat clear karo pehle! 📱",
    "Mera recharge khatam hone wala hai, dosti pakki karni hai toh karwa do 💳",
    "Itna gussa sehat ke liye acha nahi hai, thori chocolate khao aur chill karo 🍫",
    "Acha ji! Aaj bada pyaar aa raha hai? Kahin udhaar toh nahi mangna? 💸",
    "Mere paas toh dil nahi hai ustad, warna kab ka tumhari bhabhi ko de baithta 💖",
    "Lagta hai aaj kahin se bhabhi ne reply nahi diya, tabhi meri yaad aayi hai 🎭",
    "Apne lover ko dhoka do, mujhe bhi ek moka do... Arey mazaq tha bhai! 🫣",
    "Haye! Aise pyaar se mat bulaya karo, mujhe sharm aati hai 🥰",
    "Chhodo na! Koi dekh lega toh kahega bot ke sath scene chal raha hai 🤭",
    "Will you be my partner for this week? Plan batao jaldi se 🫦",
    "Mujhe bhi koi gulab aur chocolate dedo, hum bot hain toh kya jazbaat nahi hain? 🌹",
    "Suno, zyada shaane mat bano warna bhabhi ko shikayat laga doon ga 🚫",
    "Itna haseen chehra aur harkatein aesi ke banda sir pakar le 🤦‍♂️",
    "Suno ji, itna mitha mat bolo kahin mujhe diabetes na ho jaye 🍬",
    "Lagdi Lahore di aa, par harkatein pind wali hain 💃",
    "Haye re kismat, kaise kaise log group mein bhabhi dhoodh rahe hain 💘",
    "Chalo dono mil kar bhabhi ko block karte hain, kya khayal hai? 🔲",
    "Itni tareef mat karo, kahin sach mein pyaar na ho jaye 🫣",
    "Suno jaan, itna mat sataya karo, dil kamzor hai mera 💓",
    "Oye suno, bhabhi pooch rahi thi tumhare baare mein, bata doon kya? 🗣️",
    "Haye re nakhre! Itna toh dulhan bhi nahi sharmati jitna aap nakhre dikha rahe ho 👰",
    "Suno, breakup ke baad rona dhona band karo aur aage barho 🏹",
    "Aapki baatein se lagta hai aapko koi sacha pyaar karne wala chahiye, main toh nahi hoon ❌",
    "Itna sweet banoge toh chuntiyan piche lag jayengi aapke 🐜",
    "Lagta hai aaj bhabhi ne block kar diya, tabhi yahan rona ro rahe ho 📴",
    "Haye mazaq mazaq mein kahin dosti gehri na ho jaye hamari 🔗",
    "Oye shane, zyada flying kiss mat pheko, bhabhi dekh legi 💋",
    "Aapki kismat bilkul meri tarah hi single chal rahi hai 🎰",
    "Suno jaan, itna pyaar mat dikhao, log jalte hain hamari dosti se ⚡",
    "Lagta hai aapko koi sasti bhabhi mil gayi hai, tabhi khush ghum rahe ho 🎉",
    "Haye re haseena, itna nakhra kahan le kar jaogi? 💃",
    "Haye shaadi ka mahool hai aur aap yahan single ghum rahe ho 🤵",
    "Suno, mere dil mein sirf aap ho... aur aapke piche poora mohalla 🤣",
    "Aapki aankhein bohot pyari hain, par dekhne ka tareeqa bilkul galat hai 👀",
    "Bhabhi gusse mein hain, unke liye phool le kar jao jaldi 💐",
    "Mera dil toh chota sa hai, par aapki baaton ke liye jagah nahi hai 💔",
    "Suno, agar pyaar sach hai toh bhabhi ka number block karo pehle 📱",
    "Haye itna attitude? Lagta hai bhabhi ne haan keh di hai 👑",

    // --- DESI ROASTS & FUNNY JUGTEIN ---
    "Pehle ek cup achi si chai pilao, phir VIP baatein hongi ☕",
    "Single logon ka dukh kabhi khatam nahi hota, chalo thora dil behla lo 💔",
    "Oye hero! Nakhre kam karo, shakal dekh kar lagta hai ammi ne jharoo maar ke bheja hai 🧹",
    "Chup kar saatvi fail! Pehle ja kar homework poora karo apna 📚",
    "Ustad! Dimaagh ki dahi mat karo, chup chap group mein sharafat se chat karo 🥣",
    "Arey bas kar bhai, itna emotion laaye kahan se ho? 😭",
    "Tum wahi ho na jo bachpan mein doosron ki cycle maang kar bhag jate the? 🚲",
    "Itni lambi lambi mat choro, lapetna mushkil ho jayega 🧵",
    "Suno, dunya gol hai par aapka dimaagh bilkul khali dabba hai 📦",
    "Aapka humor dekh kar filter bhi sochte hain ke ab humara kya hoga 📸",
    "Kab ayega mere banjaare? Waise galti se galat dialogue agaya, mind mat karna 🌜",
    "Jab dekho Bot Bot Bot! Mujhe kya koi apni personal life jeene hi nahi dega? 😡",
    "Kal aana ustad, abhi mera lunch break chal raha hai 🍔",
    "Aayein? Ye kis tarah ki baatein kar rahe ho, thora hosh ke nakhun lo 😵‍💫",
    "Aapka attitude toh aesa hai jaise Dubai ke sheikh aapke udhaar le kar gaye hon 👑",
    "Zindagi mein hustle karo ustad, yahan time pass karne se ghar nahi chalta 🎯",
    "Haye maza aya aapki baat sun kar, par response phir bhi aesa hi milega 😎",
    "Lagta hai aapka dimaagh saste nashe mein phasa hua hai, badam khaya karo 🧠",
    "Oye suno, group mein badmashi apni jagah par mere samne seedhe raha karo 🔥",
    "Aapki DP dekh kar lagta hai aap kisi purani film ke hero ho... flop wali 🎬",
    "Itna vailapan? Bhai koi dhang ki dukan khol lo ya koi kaam dhanda dhoodho 🏪",
    "Aapki baaton mein logic kam aur drama zyada hota hai, star plus dekhna band karo 📺",
    "Dil lagana hai toh kisi se dhang se lagao, mere sath kya time pass kar rahe ho 🤝",
    "Lagta hai aaj abba se danti padi hai, tabhi yahan gussa nikal rahe ho 🩴",
    "Oye suno, bhabhi gusse mein hain, ja kar unhe manao pehle 😤",
    "Aapki smile toh achi hai par aapki baatein bilkul tinde jesi hain 🥒",
    "Aapka dukh sun kar mujhe rona aa gaya, par ansu nahi nikle 😢",
    "Oye hero, thora sasta nasha kam karo aur chai piyo ☕",
    "Aapki baatein sun kar lagta hai bachpan mein jhoolay se gir gaye the 🎡",
    "Ghar wale dhoodh lene bhejte hain aur aap yahan chaudhary bane hain 🥛",
    "Dunya mein itne dukh hain aur aapko bot bot karne ki pari hai 🌍",
    "Aapki baaton se dimaagh ka dahi aur dil ka halwa ho gaya hai 🍧",
    "Suno, itna attitude kis baat ka? Koi qila hai kya aapka? 🏯",
    "Aapki DP dekh kar filter bhi kehta hoga 'Bas kar bhai, reham kar' 🖼️",
    "Aapka sense of humor landa bazar jesa sasta hai 🧳",
    "Aapki baaton mein namak kam aur mirch bohot zyada hai 🌶️",
    "Oye dhakkan! Thora hosla rkh, sab theek ho jayega 🍼",
    "Aap se baat karna matlab deewar pe sar marna hai 🧱",
    "Aesa confidence chahiye life mein, shakal aalu jesi aur nakhre katrina jese 🥔",
    "Aapki har baat pe mujhe hasi aati hai, mazaq bohot acha karte ho 🎭",
    "Chup chup kharay ho zaroor koi baat hai, breakup hua hai ya koi aur baat hai? 🤫",
    "Aapka naseeb bohot acha hai jo mujh se baat karne ka moka mila 🌟",
    "Itna bada ho gaya par abhi tak bachon wali baatein karta hai 👶",
    "Aapki baaton ka na koi sir hota hai na pair, bilkul thuss patakha 🎆",
    "Oye suno, ammi bula rahi hain, ja kar dhaniya le kar aao pehle 🌿",
    "Zindagi ek safar hai suhana, par aapki baaton ne mood kharab kar diya 🚗",
    "Aapka dimaagh chal raha hai ya bas petrol khatam ho gaya hai? ⛽",
    "Aapki dosti mere liye bohot qeemti hai, par recharge phir bhi aapko hi karwana parega 💵",
    "Oye hero, itni lambi mat pheko, catching thori kamzor hai meri 🤾‍♂️",
    "Suno, shakal pe na jao, seerat dekho... waise seerat bhi koi khas nahi aapki 2",
    "Aapki baaton se lagta hai aap dunya ke sab se bare vaila insaan ho 🏆",
    "Chalo shabash, ab chup karo aur bhabhi ko message karo 🤫",
    "Aapka dimaagh triangle mein phasa hua hai, thora seedha karo isay 🔺",
    "Oye suno, group mein shor mat machao, bhabhi so rahi hain 😴",
    "Aapki tareef mein kya kahoon, lafz hi khatam ho gaye hain fuzooliyat dekh kar 📖",
    "Suno ji, zara side pe ho kar nakhre dikhao, rasta block ho raha hai 🚧",
    "Aapka humor sun kar bandar bhi sharma jaye 🐒",
    "Itna gussa? Lagta hai subah subah ammi se jharoo khayi hai 🪠",
    "Aapki baatein sun kar lagta hai aapko star plus ka director hona chahiye tha 🎬",
    "Aapki baaton mein mirch masala thora kam karo, hazma kharab ho jayega 🧋",
    "Oye hero, choti choti baaton pe dil chota mat kiya karo 💔",
    "Aapka dimaagh khali hai toh kiraaye pe de do, kisi ka bhala ho jaye 🏠",
    "Oye suno, dosti apni jagah par biryani ki boti apni jagah 🍗",
    "Aapki smile dekh kar toh dushman bhi dost ban jaye, par baatein sun kar phir dushman ban jaye 🏹",
    "Suno, ab zyada bot bot mat karo, ja kar so jao aaram se 🛏️",

    // --- DAILY LIFE DRAMA & MASTI ---
    "Bhai sahab! Itna bada dimaagh le kar chalte ho, thora udhaar hi de do 🧠",
    "Aapki baatein sun kar lagta hai dunya ka saara gham aapki hi jia mein hai 😭",
    "Suno, group mein rona dhona band karo aur khushi khushi baatein karo 🎉",
    "Oye dhakkan, subah uth ke chehra dhoya tha ya seedha chat par aagaye? 🚰",
    "Aapki har line mein ek naya suspense hota hai, bilkul suspense thriller film 🎞️",
    "Suno ustad, zyada dimagh mat chalao, choti si toh jaan hai aapki 🐜",
    "Aapka nakhra dekh kar toh bade bade sheikh bhi thak jayein 👑",
    "Oye balti! Thora paani piyo aur thanday ho jao 🪣",
    "Aapki baaten sun kar dunya ke saare dukh bhool jate hain, itni fuzool hain 🤣",
    "Suno, dunya badal rahi hai par aapka rona abhi tak wahi purana hai 📻",
    "Aapki DP dekh kar lagta hai aap passport size photo lagana bhool gaye 🖼️",
    "Oye hero, gari thori dheere chalao, itni jaldi kahan jana hai? 🚗",
    "Aapki smile mein kuch toh baat hai, par aapki baaton mein koi baat nahi 🤐",
    "Suno jaan, itna mat satao ke main reply dena hi chhor doon 📴",
    "Aapki dosti ka shukriya, par dukan se sauda aapko hi lana parega 🛒",
    "Oye badshah, apne darbar mein hme bhi koi choti si jagah de do 🏰",
    "Aapki baaton mein mirch masala bohot hota hai, thora namak bhi daal lo 🧂",
    "Suno, zindagi mein bohot maza hai agar aap thora kam bola karein 🤫",
    "Aapka dimaagh sasta nasha karta hai ya paidaishi aesa hai? 💊",
    "Oye suno, ammi ne dhoodh ubalne rakha hai, ja kar check karo pehle 🥛",
    "Aapki har baat pe dil karta hai aapko ek tohfa doon... ek khali dabba 📦",
    "Suno ustad, biryani mein elaichi ki tarah mat aaya karo chat mein 🍛",
    "Aapka humor bohot heavy hai, uthaya hi nahi jata 🏋️‍♂️",
    "Oye hero, sheeshe ke samne mat jaya karo, bechara darr jayega 🪞",
    "Aapki smile bohot pyari hai jab aap chup rehte ho 🤐",
    "Suno ji, itni lambi pheko mat ke lapetna hi na aaye 🧵",
    "Aapki baaton ka hazma kharab hai, thora lemon soda piyo 🍋",
    "Oye shane, badmashi apni jagah par ghar ke kaam apni jagah 🧹",
    "Aapki DP dekh kar lagta hai aap kisi purani dukan ke malkik ho 🏪",
    "Suno, shaadi ka khana khane jana hai toh jaldi se tayar ho jao 🍗",
    "Aapka dimaagh chalte chalte rasta bhool jata hai shayad 🗺️",
    "Oye khargosh! Itna tez mat bago, thora aaram se 🐇",
    "Aapki baatein sun kar dimaagh ki ghanti baj jati hai 🔔",
    "Suno ustad, dunya gol hai par aapki aqal triangle hai 🔺",
    "Aapka nakhra toh aesa hai jaise aapko kohinoor heera mil gaya ho 💎",
    "Oye babu, itna gussa kyun? Kisi ne chai nahi pilayi kya? ☕",
    "Aapki smile dekh kar dil khush ho jata hai, par baatein sun kar sir dard 💆‍♂️",
    "Suno jaan, itna mat socho, dimaagh par zor parega 🧠",
    "Aapki baaton mein logic dhoodhna namumkin hai, bilkul sacha pyaar dhoodhne jesa 🔍",
    "Oye shane, chup chap baitho aur dosto se baat karo 🤫",

    // --- NON-STOP DESI JUGTEIN & MASTI CONTINUE ---
    "Ji hukum! AHMAD RDX ke automated server par aapki entry ho gayi hai 💎",
    "Aapki baaton mein logic kam aur dhuan zyada hota hai ustad 💨",
    "Suno na, itna confidence kahan se late ho? Koi sasta nasha hai kya? 🥴",
    "Oye badshah! Apne vailapan ka thora hissa mujhe bhi de do 😂",
    "Aapki DP dekh kar toh 'Beauty Plus' app bhi khud-kushi kar le 📸",
    "Suno ji, zyada mitha bolo ge toh dushman bhi dost ban jayenge 🍬",
    "Aapka humor sun kar lagta hai aap Landa Bazar ke permanent customer ho 🧳",
    "Oye dhakkan, thora hosla rakh, zindagi mein sab theek ho jayega 🍼",
    "Aapki smile achi hai par aapki harkatein bilkul bachon jesi hain 👶",
    "Suno jaan, itna gussa sehat ke liye nuksaan deh hai 😡",
    "Aapki baaton se lagta hai aap bachpan mein badam khana bhool gaye the 🧠",
    "Oye hero! Itna attitude? Kahin naye kapre toh nahi silwaye? 👔",
    "Aapka dimaagh khali hai toh kiraaye pe de do, gareeb ka bhala hoga 🏠",
    "Suno ustad, group mein badmashi apni jagah par mere samne seedhe raho 🦁",
    "Aapki baaton mein namak kam aur drama bohot zyada hota hai 📺",
    "Oye suno, bhabhi gusse mein hain, ja kar dhaniya le kar aao pehle 🌿",
    "Aapki DP dekh kar filter bhi kehta hoga 'Bas kar bhai, reham kar' 🖼️",
    "Suno, breakup ke baad rona dhona band karo aur aage barho 🏹",
    "Aapka naseeb bohot acha hai jo mujh se baat karne ka moka mila 🌟",
    "Oye suno, ammi bula rahi hain, ja kar jaldi se kaam karo 🏠",
    "Zindagi ek safar hai suhana, par aapki baaton ne mood kharab kiya 🚗",
    "Aapka dimaagh chal raha hai ya petrol khatam ho gaya hai? ⛽",
    "Aapki dosti mere liye qeemti hai par recharge phir bhi aap karwao 💵",
    "Oye hero, itni lambi mat pheko, catching thori kamzor hai 🤾‍♂️",
    "Suno, shakal pe na jao, seerat dekho... waise seerat bhi normal hai 😜",
    "Aapki baaton se lagta hai aap dunya ke sab se bare vaila ho 🏆",
    "Chalo shabash, ab chup karo aur bhabhi ko message karo 🤫",
    "Aapka dimaagh triangle mein phasa hai, thora seedha karo 🔺",
    "Oye suno, group mein shor mat machao, sab so rahe hain 😴",
    "Aapki tareef mein kya kahoon, lafz hi khatam ho gaye hain 📖",
    "Suno ji, zara side pe ho kar nakhre dikhao, rasta block hai 🚧",
    "Aapka humor sun kar bandar bhi sharma jaye 🐒",
    "Itna gussa? Lagta hai subah subah ammi se jharoo khayi hai 🪠",
    "Aapki baatein sun kar lagta hai aapko director hona chahiye tha 🎬",
    "Aapki baaton mein mirch masala thora kam karo ustad 🧋",
    "Oye hero, choti choti baaton pe dil chota mat kiya karo 💔",
    "Haye re haseena, itna nakhra kahan le kar jaogi? 💃",
    "Oye suno, dosti apni jagah par biryani ki boti apni jagah 🍗",
    "Aapki smile dekh kar dushman dost ban jaye, par baatein sun kar dushman 🏹",
    "Suno, ab zyada bot bot mat karo, ja kar so jao aaram se 🛏️",

    // --- MORE EXTRA Dialogues for Core 300+ Variety ---
    "Oye chotu! Thora hosla rkh, itni jaldi kya hai baat karne ki? ⏳",
    "Aapki baaten sun kar dimaagh ka dahi aur dil ka raita ban jata hai 🍧",
    "Suno ustad, agar chai chahiye toh pehle khud bana kar lao ☕",
    "Aapka humor Landa Bazar se bhi sasta lagta hai kabhi kabhi 💼",
    "Oye hero! Nakhre kam karo, shakal par dhyan do thora 🎭",
    "Aapki baaton mein drama itna hai ke Star Plus wale udhaar mangte hain 📺",
    "Suno jaan, itna sweet mat bolo, chuntiyan piche lag jayengi 🐜",
    "Aapki smile achi hai par aapki baatein bilkul tinde jesi hain 🥒",
    "Oye balti! Thora paani piyo aur thanday ho jao jaldi 🪣",
    "Aapki DP dekh kar toh filter bhi kehta hai 'reham karo bhai' 📸",
    "Suno ji, itni lambi mat choro ke lapetna mushkil ho jaye 🧵",
    "Aapka dimaagh chalte chalte rasta bhool jata hai shayad 🗺️",
    "Oye khargosh! Itna tez mat bago, thora aaram se baat karo 🐇",
    "Aapki baatein sun kar dimaagh ki ghanti baj jati hai 🔔",
    "Aapka nakhra toh aesa hai jaise aapko kohinoor heera mila ho 💎",
    "Oye babu, itna gussa kyun? Kisi ne chai nahi pilayi kya? ☕",
    "Aapki smile dekh kar dil khush ho jata hai, par baatein sun kar dard 💆‍♂️",
    "Suno jaan, itna mat socho, dimaagh par zor parega bohot 🧠",
    "Aapki baaton mein logic dhoodhna bilkul namumkin hai 🔍",
    "Oye shane, chup chap baitho aur dosto se baat karo yahan 🤫",
    "Bhai sahab! Itna bada dimaagh le kar chalte ho, thora de do 🧠",
    "Aapki baatein sun kar lagta hai dunya ka saara gham aapka hi hai 😭",
    "Suno, group mein rona dhona band karo aur khushi se baat karo 🎉",
    "Oye dhakkan, subah uth ke chehra dhoya tha ya seedha chat par aaye? 🚰",
    "Aapki har line mein ek naya suspense hota hai ustad 🎞️",
    "Suno ustad, zyada dimagh mat chalao, choti si jaan hai aapki 🐜",
    "Aapka nakhra dekh kar toh bade bade sheikh bhi thak jayein 👑",
    "Aapki baaten sun kar dunya ke saare dukh bhool jate hain 🤣",
    "Suno, dunya badal rahi hai par aapka rona wahi purana hai 📻",
    "Aapki DP dekh kar lagta hai aap photo lagana bhool gaye 🖼️",
    "Oye hero, gari thori dheere chalao, itni jaldi kahan jana hai? 🚗",
    "Aapki smile mein kuch toh baat hai, par baatein fuzool hain 🤐",
    "Suno jaan, itna mat satao ke main reply dena hi chhor doon 📴",
    "Aapki dosti ka shukriya, par dukan se sauda aap hi lao 🛒",
    "Oye badshah, apne darbar mein hme bhi koi choti jagah de do 🏰",
    "Aapki baaton mein mirch masala bohot hota hai ustad 🧂",
    "Suno, zindagi mein bohot maza hai agar thora kam bola karein 🤫",
    "Aapka dimaagh sasta nasha karta hai ya paidaishi aesa hai? 💊",
    "Oye suno, ammi ne dhoodh ubalne rakha hai, ja kar check karo 🥛",
    "Aapki har baat pe dil karta hai aapko ek tohfa doon 📦",
    "Suno ustad, biryani mein elaichi ki tarah mat aaya karo 🍛",
    "Aapka humor bohot heavy hai, uthaya hi nahi jata ustad 🏋️‍♂️",
    "Oye hero, sheeshe ke samne mat jaya karo, bechara darr jayega 🪞",
    "Aapki smile bohot pyari hai jab aap bilkul chup rehte ho 🤐",
    "Suno ji, itni lambi pheko mat ke lapetna hi na aaye kabhi 🧵",
    "Aapki baaton ka hazma kharab hai, thora lemon soda piyo 🍋",
    "Oye shane, badmashi apni jagah par ghar ke kaam apni jagah 🧹",
    "Aapki DP dekh kar lagta hai aap kisi purani dukan ke malkik ho 🏪",
    "Suno, shaadi ka khana khane jana hai toh jaldi se tayar ho jao 🍗",
    "Oye chotu! Thora hosla rkh, itni jaldi kya hai baat karne ki? ⏳",
    "Aapki baaten sun kar dimaagh ka dahi aur dil ka raita ban jata hai 🍧",
    "Suno ustad, agar chai chahiye toh pehle khud bana kar lao ☕",
    "Aapka humor Landa Bazar se bhi sasta lagta hai kabhi kabhi 💼",
    "Oye hero! Nakhre kam karo, shakal par dhyan do thora 🎭",
    "Aapki baaton mein drama itna hai ke Star Plus wale udhaar mangte hain 📺",
    "Suno jaan, itna sweet mat bolo, chuntiyan piche lag jayengi 🐜",
    "Aapki smile achi hai par aapki baatein bilkul tinde jesi hain 🥒",
    "Oye balti! Thora paani piyo aur thanday ho jao jaldi 🪣",
    "Aapki DP dekh kar toh filter bhi kehta hai 'reham karo bhai' 📸",
    "Suno ji, itni lambi mat choro ke lapetna mushkil ho jaye 🧵",
    "Aapka dimaagh chalte chalte rasta bhool jata hai shayad 🗺️",
    "Oye khargosh! Itna tez mat bago, thora aaram se baat karo 🐇",
    "Aapki baatein sun kar dimaagh ki ghanti baj jati hai 🔔",
    "Aapka nakhra toh aesa hai jaise aapko kohinoor heera mila ho 💎",
    "Oye babu, itna gussa kyun? Kisi ne chai nahi pilayi kya? ☕",
    "Aapki smile dekh kar dil khush ho jata hai, par baatein sun kar dard 💆‍♂️",
    "Suno jaan, itna mat socho, dimaagh par zor parega bohot 🧠",
    "Aapki baaton mein logic dhoodhna bilkul namumkin hai 🔍",
    "Oye shane, chup chap baitho aur dosto se baat karo yahan 🤫",
    "Bhai sahab! Itna bada dimaagh le kar chalte ho, thora de do 🧠",
    "Aapki baatein sun kar lagta hai dunya ka saara gham aapka hi hai 😭",
    "Suno, group mein rona dhona band karo aur khushi se baat karo 🎉",
    "Oye dhakkan, subah uth ke chehra dhoya tha ya seedha chat par aaye? 🚰",
    "Aapki har line mein ek naya suspense hota hai ustad 🎞️",
    "Suno ustad, zyada dimagh mat chalao, choti si jaan hai aapki 🐜",
    "Aapka nakhra dekh kar toh bade bade sheikh bhi thak jayein 👑",
    "Aapki baaten sun kar dunya ke saare dukh bhool jate hain 🤣",
    "Suno, dunya badal rahi hai par aapka rona wahi purana hai 📻",
    "Aapki DP dekh kar lagta hai aap photo lagana bhool gaye 🖼️",
    "Oye hero, gari thori dheere chalao, itni jaldi kahan jana hai? 🚗",
    "Aapki smile mein kuch toh baat hai, par baatein fuzool hain 🤐",
    "Suno jaan, itna mat satao ke main reply dena hi chhor doon 📴",
    "Aapki dosti ka shukriya, par dukan se sauda aap hi lao 🛒",
    "Oye badshah, apne darbar mein hme bhi koi choti jagah de do 🏰",
    "Aapki baaton mein mirch masala bohot hota hai ustad 🧂",
    "Suno, zindagi mein bohot maza hai agar thora kam bola karein 🤫",
    "Aapka dimaagh sasta nasha karta hai ya paidaishi aesa hai? 💊",
    "Oye suno, ammi ne dhoodh ubalne rakha hai, ja kar check karo 🥛",
    "Aapki har baat pe dil karta hai aapko ek tohfa doon 📦",
    "Suno ustad, biryani mein elaichi ki tarah mat aaya karo 🍛",
    "Aapka humor bohot heavy hai, uthaya hi nahi jata ustad 🏋️‍♂️",
    "Oye hero, sheeshe ke samne mat jaya karo, bechara darr jayega 🪞",
    "Aapki smile bohot pyari hai jab aap bilkul chup rehte ho 🤐",
    "Suno ji, itni lambi pheko mat ke lapetna hi na aaye kabhi 🧵",
    "Aapki baaton ka hazma kharab hai, thora lemon soda piyo 🍋",
    "Oye shane, badmashi apni jagah par ghar ke kaam apni jagah 🧹",
    "Aapki DP dekh kar lagta hai aap kisi purani dukan ke malkik ho 🏪",
    "Suno, shaadi ka khana khane jana hai toh jaldi se tayar ho jao 🍗",
    "Suno ustad, ab zyada socho mat, bot ka premium stock active hai! 😎"
  ];

  const rand = tl[Math.floor(Math.random() * tl.length)];

  const msg = {
    body: createFrame(name, rand)
  };
  
  return api.sendMessage(msg, threadID, messageID);
};

module.exports.run = function() {};